# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Site Settings
title                    : "Hyeonmin Yun"
description              : "Hyeonmin Yun's Personal Website"
repository               : "hyeonmin-yun/hyeonmin-yun.github.io"
google_scholar_stats_use_cdn : true
# -----------------------
# [2] 분석 및 SEO (일단 비워둬도 됩니다)
# -----------------------
google_analytics_id      :  # 나중에 구글 애널리틱스 연동 시 입력
google_site_verification :
bing_site_verification   :
baidu_site_verification  :

# -----------------------
# [3] 저자 프로필 (화면에 표시되는 정보)
# -----------------------
author:
  name             : "본인 영문 이름"    # 예: Gil-Dong Hong
  avatar           : "images/profile.jpg" # images 폴더에 본인 사진을 넣고 파일명 수정
  bio              : "PhD Student in AI<br>Interested in Sampling, AI4Science & Geometry" # 줄바꿈은 <br> 사용
  location         : "Seoul, South Korea"
  email            : "본인이메일@univ.ac.kr" # 연락 받을 이메일
  
  # 학술/소셜 링크 (있는 것만 채우고 나머지는 비워두세요)
  googlescholar    : "https://scholar.google.com/citations?user=본인_ID"
  github           : "본인깃허브아이디"
  linkedin         : "본인링크드인ID" # (선택 사항)
  researchgate     :  # (선택 사항)
  twitter          :  # (선택 사항)
  # 필요한 다른 소셜 링크가 있다면 아래 형식 유지하며 작성

# -----------------------
# [4] 파일 읽기 설정 (건드리지 않음)
# -----------------------
include:
  - .htaccess
  - _pages
  - files
exclude:
  - docs
  - google_scholar_crawler
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - .github
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# -----------------------
# [5] 변환 및 마크다운 설정 (기본값 유지)
# -----------------------
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default
      author_profile: true

# -----------------------
# [6] 디자인 및 시간대
# -----------------------
sass:
  sass_dir: _sass
  style: compressed

permalink: /:categories/:title/
timezone: Asia/Seoul  # <-- 한국 시간대로 변경했습니다.

# -----------------------
# [7] 플러그인 (기본값 유지)
# -----------------------
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from

whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

compress_html:
  clippings: all
  ignore:
    envs: development